config/routes.rb
Rails.application.routes.draw do


devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}



  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    get '/' => 'homes#top'

    resources :customers, only: [:show] do
      resources :orders, only: [:index]
    end
  end


  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:index, :new, :show, :create] do
      collection do
        post 'confirm'
        get 'thanks'
      end
    end
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :customers, only: [:show, :edit, :update] do
    patch 'customers/withdrawal'
    get 'customers/unsubscribe'
  end
    get 'customers/my_page', to: 'customers#show', as: :customers_my_page
    patch 'information', to: 'customers#update', as: :costomers_information_update
    get 'customers/information/edit', to: 'customers#edit', as: :customers_information_edit
    resources :items, only: [:index, :show]
  end

  root to: 'homes#top'
  get '/homes/top' => 'homes#top', as: 'top'
  get '/homes/about' => 'homes#about', as: 'about'
  
  get 'keyword/search', to: 'searches#keyword_search', as: 'keyword_search'
  get 'genre/search', to: 'searches#genre_search', as: 'genre_search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/address.rb
class Address < ApplicationRecord

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  
  belongs_to :customer

  validates :postal_code, presence: true, length: { is: 7 }, numericality: { only_integer: true }
  validates :address, presence: true
  validates :name, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true, numericality: {only_integer: true, greater_than: 0}


  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  def full_name
    self.last_name + " " + self.first_name
  end
  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  # 退会済みかチェックするメソッド
  def active_for_authentication?
    super && self.is_active
  end
  
  has_many :addresses, dependent: :destroy
  
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false, message: "はすでに存在しています" }
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  has_many :orders, through: :order_details

  has_one_attached :image

  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true, length: { maximum:150 }
  validates :price, presence:true
  validates :is_active, inclusion: {in: [true, false]}

  scope :active, -> { where(is_active: true) }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end

  scope :search_by_keyword, -> (keyword) {
    where("items.name LIKE ? OR genres.name LIKE ?", "%#{keyword}%", "%#{keyword}%" ).joins(:genre)
  }


end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}




  #enum status: { deposit_pending: 0, payment_confirmed: 1, in_making: 2, preparing_shipment: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3, }





  #enum making_status: { not_started: 0, pending: 1, in_progress: 2, completed: 3, }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    @orders = Order.order(created_at: :desc).page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    if @item.save
      redirect_to admin_item_path(@item), notice: '商品を登録しました'
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      @genres = Genre.all
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number] )
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.order(created_at: :desc).limit(4)
    @genres = Genre.all
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  #items_controllerに記載
  def keyword_search
    @genres = Genre.all
    @keyword = params[:keyword].to_s.strip.gsub(/[\s　]+/, " ")
    if @keyword.present?
      @items = Item.search_by_keyword(@keyword).page(params[:page]).per(8)
    else
      redirect_to root_path
    end
  end

  def genre_search
    @genre_id = params[:genre_id]
    @genre = Genre.find(@genre_id)
    @genres = Genre.all
    @items = Item.where(genre_id: @genre_id).page(params[:page]).per(8)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admin/items/_edit.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-lg-9 col-md-6">
    <%= form_with url: admin_item_path, model: @item do |f| %>

      <div class="row justify-content-center">
        <div>
          <table>
            <tr class="my-2">
              <td class="py-3">商品画像</td>
              <td class="pl-5"><%= f.file_field :image, accept: "image/*" %></td>
            </tr>
            <tr class="my-2">
              <td class="py-3">商品名</td>
              <td class="pl-5"><%= f.text_field :name, placeholder: "商品名", class:'form-control' %></td>
            </tr>
            <tr class="my-2">
              <td class="py-3 align-top">商品説明</td>
              <td class="pl-5"><%= f.text_area :introduction, class:'form-control', rows:6, placeholder: "ここに説明文を記述します" %></td>
            </tr>
            <tr class="my-2">
              <td class="py-3">ジャンル</td>
              <td class="pl-5"><%= f.select :genre_id, options_from_collection_for_select(@genres, :id, :name, @item.genre_id), { include_blank: "~選択してください~" }, class:'form-control' %></td>
            </tr>
            <tr class="my-2">
              <td class="py-3">税込価格</td>
              <td class="pl-5">
                <div class="input-group">
                  <%= f.text_field :price, class: 'form-control', placeholder: "1000" %>
                  <div class="input-group-append">
                    <span class="input-group-text">円</span>
                  </div>
                </div>
              </td>
            </tr>
            <tr class="my-2">
              <td class="py-3">販売ステータス</td>
              <td class="pl-5">
                <%= f.radio_button :is_active, true %>
                <%= f.label :is_active_true, "販売中" %>
                <%= f.radio_button :is_active, false %>
                <%= f.label :is_active_false, "販売停止中" %>
              </td>
            </tr>
          </table>
        </div>
      </div>
        
      <div class="row justify-content-center">
        <%= f.submit '変更を保存', class:'btn btn-success btn-lg' %>
      </div>

    <% end %>

  </div>
</div>

app/views/admin/items/_form.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-lg-9 col-md-6">
    <%= form_with url: admin_items_path, model: @item do |f| %>

      <div class="row justify-content-center">
        <div>
          <table>
            <tr class="my-2">
              <td class="py-3">商品画像</td>
              <td class="pl-5"><%= f.file_field :image, accept: "image/*" %></td>
            </tr>
            <tr class="my-2">
              <td class="py-3">商品名</td>
              <td class="pl-5"><%= f.text_field :name, placeholder: "商品名", class:'form-control' %></td>
            </tr>
            <tr class="my-2">
              <td class="py-3 align-top">商品説明</td>
              <td class="pl-5"><%= f.text_area :introduction, class:'form-control', rows:6, placeholder: "ここに説明文を記述します" %></td>
            </tr>
            <tr class="my-2">
              <td class="py-3">ジャンル</td>
              <td class="pl-5"><%= f.select :genre_id, options_from_collection_for_select(@genres, :id, :name), { include_blank: "~選択してください~" }, class:'form-control' %></td>
            </tr>
            <tr class="my-2">
              <td class="py-3">税込価格</td>
              <td class="pl-5">
                <div class="input-group">
                  <%= f.text_field :price, class: 'form-control', placeholder: "1000" %>
                  <div class="input-group-append">
                    <span class="input-group-text">円</span>
                  </div>
                </div>
              </td>
            </tr>
            <tr class="my-2">
              <td class="py-3">販売ステータス</td>
              <td class="pl-5">
                <%= f.radio_button :is_active, true %>
                <%= f.label :is_active_true, "販売中" %>
                <%= f.radio_button :is_active, false %>
                <%= f.label :is_active_false, "販売停止中" %>
              </td>
            </tr>
          </table>
        </div>
      </div>
        
      <div class="row justify-content-center">
        <%= f.submit '新規登録', class:'btn btn-success btn-lg' %>
      </div>

    <% end %>

  </div>
</div>

app/views/admin/items/_index.html.erb
<div class="row mt-2 justify-content-center">
  <div class="col-10">
    <table class="table">
      <thead style="background-color: #E6E6E6;">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td>
              <%= link_to admin_item_path(item.id), class:'text-dark', style: 'text-decoration: underline' do %>
                <%= item.name %>
              <% end %>
            </td>
            <td><%= number_with_delimiter(item.price) %></td>
            <td><%= item.genre.name %></td>
            <% if item.is_active == true %>
              <td class="text-success"><strong>販売中</strong></td>
            <% else %>
              <td class="text-secondary"><strong>販売停止中</strong></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate items %>
  </div>
</div>

app/views/admin/items/_show.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <%= image_tag item.get_image(300, 200) %>
    </div>

    <div class="col-8">
      <table>
        <tbody>
          <tr class="my-2">
            <td class="py-2">商品名</td>
            <td class="pl-3"><%= item.name %></td>
          </tr>
          <tr class="my-2">
            <td class="py-2">商品説明</td>
            <td class="pl-3"><%= item.introduction %></td>
          </tr>
          <tr class="my-2">
            <td class="py-2">ジャンル</td>
            <td class="pl-3"><%= item.genre.name %></td>
          </tr>
          <tr class="my-2">
            <td class="py-2">
              税込価格<br>
              (税抜き価格)
            </td>
            <td class="pl-3">
              <%= number_with_delimiter((item.price * 1.1).to_i) %>
              (<%= number_with_delimiter(item.price) %>)円
            </td>
          </tr>
          <tr class="my-2">
            <td class="py-2">販売ステータス</td>
            <% if item.is_active == true %>
              <td class="text-success pl-3">販売中</td>
            <% else %>
              <td class="text-secondary pl-3">販売停止中</td>
            <% end %>
          </tr>
        </tbody>
      </table>

    </div>

  </div>
  <div class="row justify-content-center mt-4">
    <%= link_to '編集する', edit_admin_item_path, class:'btn btn-success btn-lg' %>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row mb-3">
    <h4 style="background-color: #E6E6E6;">商品編集</h4>
  </div>

  <%= render 'layouts/errors', obj:@item %>

  <%= render 'edit', item:@item %>
</div>

app/views/admin/items/index.html.erb
<div class="container">

  <div class="row mt-5 justify-content-center">
    <div class="col-9 d-flex justify-content-between align-items-center">

        <span><h4 style="background-color: #E6E6E6;">商品一覧</h4></span>
        <%= link_to new_admin_item_path, style:'color:#000000;' do %>
          <%= image_tag "plus-icon.png", size:"100x100", style:'border-radius: 50%;' %>
        <% end %>

    </div>
  </div>

  <%= render 'index', items:@items %>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row mb-3">
    <h4>商品新規登録</h4>
  </div>

  <%= render 'layouts/errors', obj:@item %>

  <%= render 'form', item:@item %>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row mb-3">
    <h4 style="background-color: #E6E6E6;">商品詳細</h4>
  </div>
 
  <%= render 'show', item:@item %>

</div>