config/routes.rb
Rails.application.routes.draw do


devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}



  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    get '/' => 'homes#top'

    resources :customers, only: [:show] do
      resources :orders, only: [:index]
    end
  end


  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:index, :new, :show, :create] do
      collection do
        post 'confirm'
        get 'thanks'
      end
    end
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :customers, only: [:show, :edit, :update] do
    patch 'customers/withdrawal'
    get 'customers/unsubscribe'
  end
    get 'customers/my_page', to: 'customers#show', as: :customers_my_page
    patch 'information', to: 'customers#update', as: :costomers_information_update
    get 'customers/information/edit', to: 'customers#edit', as: :customers_information_edit
    resources :items, only: [:index, :show]
  end

  root to: 'homes#top'
  get '/homes/top' => 'homes#top', as: 'top'
  get '/homes/about' => 'homes#about', as: 'about'
  
  get 'keyword/search', to: 'searches#keyword_search', as: 'keyword_search'
  get 'genre/search', to: 'searches#genre_search', as: 'genre_search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}




  #enum status: { deposit_pending: 0, payment_confirmed: 1, in_making: 2, preparing_shipment: 3, shipped: 4 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def index
    @customer = Customer.find_by(id: params[:customer_id])
    if @customer.nil?
      redirect_to admin_customers_path, alert: "会員が見つかりません。"
    else
      @orders = @customer.orders.includes(order_details: :item).order(created_at: :desc).page(params[:page])
    end
  end

  def update
    @order = Order.find(params[:id])
    status = params[:order][:status]
  
    case status
    when "入金待ち", "入金確認"
      if @order.update(order_params)
        if status == "入金確認"
          @order.order_details.update_all(making_status: "製作待ち")
          flash[:notice] = '注文ステータスが更新されました。製作ステータスが製作待ちになりました。'
        else
          flash[:notice] = '注文ステータスが更新されました。'
        end
        redirect_to admin_order_path(@order)
      else
        flash[:alert] = '注文ステータスの更新に失敗しました。'
        redirect_to admin_order_path(@order)
      end
    when "製作中"
      flash[:alert] = 'こちらは手動で変えられません。製作ステータスが更新されるまでお待ちください。'
      redirect_to admin_order_path(@order)
    when "発送準備中"
      flash[:alert] = 'こちらは手動で変えられません。製作ステータスが全て製作完了になるまでお待ちください。'
      redirect_to admin_order_path(@order)
    when "発送済み"
      if @order.order_details.all? { |order_detail| order_detail.making_status == "製作完了" }
        if @order.update(order_params)
          flash[:notice] = '注文ステータスが更新されました。発送済みになりました。'
        else
          flash[:alert] = '注文ステータスの更新に失敗しました。'
        end
        redirect_to admin_order_path(@order)
      else
        flash[:alert] = '製作ステータスが全て製作完了になるまでお待ちください。'
        redirect_to admin_order_path(@order)
      end
    else
      flash[:alert] = '注文ステータスの更新に失敗しました。'
      redirect_to admin_order_path(@order)
    end
  end


  private

  def order_params
    params.require(:order).permit(:status)
  end
  
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<% if flash[:alert] %>
  <%= flash[:alert] %>
<% end %>

<div class="container">
  <div class="row">
    <h4 class = "col-4 my-3 mx-5 text-center" style = "background-color: #E6E6E6;">
    <%= @customer.last_name + @customer.first_name %> さんの注文履歴</h4>
  </div>
</div>

<div class="container">
  <div class="row mx-5">
    <% if @orders.present? %>
      <table class="table table-hover">
        <thead>
          <tr class="table-active">
            <th class="col-2">購入日時</th>
            <th class="col-2">注文個数</th>
            <th class="col-2">注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_order_path(order) %></td>
              <td><%= order.order_details.sum(:amount) %></td>
              <td><%= order.status_i18n %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= paginate @orders %>

    <% else %>
      <p class="text-center">注文履歴が見つかりません。</p>
    <% end %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<% if flash[:alert] %>
  <%= flash[:alert] %>
<% end %>



<div class="container mt-3">
  <div class="row">
    <h4 class = "col-2 text-center" style="background-color: #E6E6E6;">注文履歴詳細</h4>
  </div>

  <div class="row my-2">
    <strong class="col-2">購入者</strong>
    <div class="col-6">
      <%= link_to admin_customer_path(@order.customer) do %>
        <%= @order.customer.last_name %>
        <%= @order.customer.first_name %>
      <% end %>
    </div>
  </div>
  <div class="row my-2">
    <strong class="col-2">注文日</strong>
    <div class="col-6">
      <%= @order.created_at.strftime('%Y/%m/%d') %>
    </div>
  </div>
  <div class="row my-2">
    <strong class="col-2">配送先</strong>
    <div class="col-6">〒<%= @order.postal_code %> <%= @order.address %>
      <br />
      <%= @order.name %>
    </div>
  </div>
  <div class="row my-2">
    <strong class="col-2">支払方法</strong>
    <div class="col-6"><%= @order.payment_method_i18n %></div>
  </div>
  <div class="row my-2">
    <strong class="col-2">注文ステータス</strong>
    <div class="col-6">
      <%= form_with model:@order, url: admin_order_path(@order), method: :patch, local: true do |f| %>
        <%= f.select :status, Order.statuses.keys,{} %>
       
        <%= f.submit "更新", class: "btn btn-success mx-3" %>
      <% end %>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-9">
      <table class="table table-hover">
        <thead class="table-active">
          <tr>
            <th class="col-2">商品名</th>
            <th class="col-2">単価（税込）</th>
            <th class="col-1">数量</th>
            <th class="col-1">小計</th>
            <th class="col-3">製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= number_to_currency(order_detail.price) %></td>
              <td><%= order_detail.amount %>個</td>
              <td><%= number_to_currency(order_detail.price * order_detail.amount) %></td>
              <td>
                <%= form_with model:order_detail, url: admin_order_detail_path(order_detail), method: :patch, local: true do |f|  %>
                  <%= f.select :making_status, OrderDetail.making_statuses.keys,{} %>
                  <%= f.submit '更新', class: "btn btn-success mx-5" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-3 align-items-end">
      <table>
        <tr>
          <th class="col-2">商品合計</th>
          <td class="col-1 text-right"><%= number_to_currency(@order.total_payment) %>
          </td>
        </tr>
        <tr>
          <th class="col-2">送料</strong></th>
          <td class="col-1 text-right"><%= number_to_currency(@order.shipping_cost) %>
          </td>
        </tr>
        <tr>
          <th class="col-2">請求合計金額</th>
          <td class="col-1 text-right"><%= number_to_currency(@order.total_payment + @order.shipping_cost) %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>