config/routes.rb
Rails.application.routes.draw do


devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}



  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    get '/' => 'homes#top'

    resources :customers, only: [:show] do
      resources :orders, only: [:index]
    end
  end


  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:index, :new, :show, :create] do
      collection do
        post 'confirm'
        get 'thanks'
      end
    end
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :customers, only: [:show, :edit, :update] do
    patch 'customers/withdrawal'
    get 'customers/unsubscribe'
  end
    get 'customers/my_page', to: 'customers#show', as: :customers_my_page
    patch 'information', to: 'customers#update', as: :costomers_information_update
    get 'customers/information/edit', to: 'customers#edit', as: :customers_information_edit
    resources :items, only: [:index, :show]
  end

  root to: 'homes#top'
  get '/homes/top' => 'homes#top', as: 'top'
  get '/homes/about' => 'homes#about', as: 'about'
  
  get 'keyword/search', to: 'searches#keyword_search', as: 'keyword_search'
  get 'genre/search', to: 'searches#genre_search', as: 'genre_search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/address.rb
class Address < ApplicationRecord

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  
  belongs_to :customer

  validates :postal_code, presence: true, length: { is: 7 }, numericality: { only_integer: true }
  validates :address, presence: true
  validates :name, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true, numericality: {only_integer: true, greater_than: 0}


  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  def full_name
    self.last_name + " " + self.first_name
  end
  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  # 退会済みかチェックするメソッド
  def active_for_authentication?
    super && self.is_active
  end
  
  has_many :addresses, dependent: :destroy
  
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false, message: "はすでに存在しています" }
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  has_many :orders, through: :order_details

  has_one_attached :image

  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true, length: { maximum:150 }
  validates :price, presence:true
  validates :is_active, inclusion: {in: [true, false]}

  scope :active, -> { where(is_active: true) }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end

  scope :search_by_keyword, -> (keyword) {
    where("items.name LIKE ? OR genres.name LIKE ?", "%#{keyword}%", "%#{keyword}%" ).joins(:genre)
  }


end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}




  #enum status: { deposit_pending: 0, payment_confirmed: 1, in_making: 2, preparing_shipment: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3, }





  #enum making_status: { not_started: 0, pending: 1, in_progress: 2, completed: 3, }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    @orders = Order.order(created_at: :desc).page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    if @item.save
      redirect_to admin_item_path(@item), notice: '商品を登録しました'
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      @genres = Genre.all
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number] )
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.order(created_at: :desc).limit(4)
    @genres = Genre.all
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  #items_controllerに記載
  def keyword_search
    @genres = Genre.all
    @keyword = params[:keyword].to_s.strip.gsub(/[\s　]+/, " ")
    if @keyword.present?
      @items = Item.search_by_keyword(@keyword).page(params[:page]).per(8)
    else
      redirect_to root_path
    end
  end

  def genre_search
    @genre_id = params[:genre_id]
    @genre = Genre.find(@genre_id)
    @genres = Genre.all
    @items = Item.where(genre_id: @genre_id).page(params[:page]).per(8)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <h4 class = "col-2 my-3 mx-5 text-center" style = "background-color: #E6E6E6;">注文履歴一覧</h4>
  </div>
</div>

<div class="container">
  <div class="row mx-5">
    <% if @orders.present? %>
      <table class="table table-hover">
        <thead>
          <tr class="table-active">
            <th class="col-2">購入日時</th>
            <th class="col-2">購入者</th>
            <th class="col-2">注文個数</th>
            <th class="col-2">注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_order_path(order) %></td>
              <td>
              <%= order.customer.last_name %>
              <%= order.customer.first_name %>
              </td>
              <td><%= order.order_details.sum(:amount) %></td>
              <td><%= order.status_i18n %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= paginate @orders %>

    <% else %>
      <p class="text-center">注文履歴が見つかりません。</p>
    <% end %>
  </div>
</div>

app/views/homes/_genre_index.html.erb
<div class="col-2">
  <div class="border border-dark" style="height: 300px;">
    <p class="text-center border-bottom border-dark mt-1">ジャンル検索</p>

    <ul class="p-0 ml-2" style="list-style: none;">
      <% genres.each do |genre| %>
        <li class="mx-3 my-2"><%= link_to genre.name, genre_search_path(genre_id: genre.id), method: :get, style:'color:#000000;' %></li>
      <% end %>
    </ul>

  </div>
</div>

app/views/homes/about.html.erb
<div class="container">

  <div class="row justify-content-center my-4">
    <h1 class="font-weight-bold" style="font-size:90px;">About</h1>
  </div>

  <div class="row justify-content-center">
    <p class="text-center" style="font-size: 32px;">
      ながのCAKEは全国発送可能なケーキ屋さんです。<br>
      お子様からお年寄りまでお召し上がりいただけるよう、<br>
      様々なバリエーションをご用意しております。<br>
      また、全国発送可能ですので、「いつ」でも「どこ」でもご注文いただけます。<br>
      ぜひご注文ください。
    </p>
  </div>

  <div class="row justify-content-center">
    <%= image_tag 'christmas_cake.png', size:'300x200' %>
  </div>

</div>

app/views/homes/top.html.erb
<div class="container">

  <div class="row mt-5">

    <%= render 'homes/genre_index', genres:@genres %>

    <div class="col-9 offset-1">

      <div class="row border-dark" style="height: 300px;">
        <div class="col-6 offset-2">
          <p class="mt-5 pt-4 align-baseline border border-dark" style="height: 150px;">
            ようこそ、ながのCAKEへ！<br>
            このサイトは、ケーキ販売のECサイトになります。<br>
            会員でない方も商品の閲覧はできますが、<br>
            購入には会員登録が必要になります。<br>
          </p>
        </div>
      </div>

      <div class="row ml-2 mb-2">
        <h2 class="fs-2 font-weight-bold">新着商品</h2>
      </div>

      <div class="row">

        <% @items.each do |item| %>
          <div class="col-3">
            <%= link_to item_path(item.id) do %>
              <%= image_tag item.get_image(200, 100) %>
            <% end %>
            <p><strong><%= item.name %></strong></p>
            <p><strong>¥<%= number_with_delimiter(item.price) %></strong></p>
          </div>
        <% end %>

        
      </div>

      <div class="row justify-content-end">
        <div class="col-2 offset-10 p-0">
          <%= link_to '全ての商品を見る >', items_path, class:'text-center', style:'text-decoration: underline;' %>
        </div>
      </div>

    </div>
  </div>
</div>