config/routes.rb
Rails.application.routes.draw do


devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}



  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    get '/' => 'homes#top'

    resources :customers, only: [:show] do
      resources :orders, only: [:index]
    end
  end


  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:index, :new, :show, :create] do
      collection do
        post 'confirm'
        get 'thanks'
      end
    end
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :customers, only: [:show, :edit, :update] do
    patch 'customers/withdrawal'
    get 'customers/unsubscribe'
  end
    get 'customers/my_page', to: 'customers#show', as: :customers_my_page
    patch 'information', to: 'customers#update', as: :costomers_information_update
    get 'customers/information/edit', to: 'customers#edit', as: :customers_information_edit
    resources :items, only: [:index, :show]
  end

  root to: 'homes#top'
  get '/homes/top' => 'homes#top', as: 'top'
  get '/homes/about' => 'homes#about', as: 'about'
  
  get 'keyword/search', to: 'searches#keyword_search', as: 'keyword_search'
  get 'genre/search', to: 'searches#genre_search', as: 'genre_search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/address.rb
class Address < ApplicationRecord

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  
  belongs_to :customer

  validates :postal_code, presence: true, length: { is: 7 }, numericality: { only_integer: true }
  validates :address, presence: true
  validates :name, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true, numericality: {only_integer: true, greater_than: 0}


  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  def full_name
    self.last_name + " " + self.first_name
  end
  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  # 退会済みかチェックするメソッド
  def active_for_authentication?
    super && self.is_active
  end
  
  has_many :addresses, dependent: :destroy
  
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false, message: "はすでに存在しています" }
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  has_many :orders, through: :order_details

  has_one_attached :image

  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true, length: { maximum:150 }
  validates :price, presence:true
  validates :is_active, inclusion: {in: [true, false]}

  scope :active, -> { where(is_active: true) }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end

  scope :search_by_keyword, -> (keyword) {
    where("items.name LIKE ? OR genres.name LIKE ?", "%#{keyword}%", "%#{keyword}%" ).joins(:genre)
  }


end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}




  #enum status: { deposit_pending: 0, payment_confirmed: 1, in_making: 2, preparing_shipment: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3, }





  #enum making_status: { not_started: 0, pending: 1, in_progress: 2, completed: 3, }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number] )
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.order(created_at: :desc).limit(4)
    @genres = Genre.all
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  #items_controllerに記載
  def keyword_search
    @genres = Genre.all
    @keyword = params[:keyword].to_s.strip.gsub(/[\s　]+/, " ")
    if @keyword.present?
      @items = Item.search_by_keyword(@keyword).page(params[:page]).per(8)
    else
      redirect_to root_path
    end
  end

  def genre_search
    @genre_id = params[:genre_id]
    @genre = Genre.find(@genre_id)
    @genres = Genre.all
    @items = Item.where(genre_id: @genre_id).page(params[:page]).per(8)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_header.html.erb
       
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
   

    <ul class="navbar-nav ml-auto">
        
      <li>
        <%=  link_to admin_items_path,class: 'nav-link text-dark' do %>
        <span class="boxed"> 商品一覧 </span>
        <% end %>
      </li>
      <li>
        <%= link_to admin_customers_path,class: 'nav-link text-dark' do %>
        <span class="boxed"> 会員一覧 </span>
        <% end %>
      </li>
      <li>
        <%=  link_to admin_path ,class: 'nav-link text-dark' do %>
        <span class="boxed"> 注文履歴一覧 </span>
        <% end %>
      </li>
      <li>
        <%= link_to admin_genres_path, class: 'nav-link text-dark' do %>
        <span class="boxed"> ジャンル一覧 </span>
        <% end %>
      </li>
      <li>
        <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-dark' do %>
        <span class="boxed"> ログアウト </span>
        <% end %>
      </li>
    </ul>

  </div>
    
    

app/views/layouts/_customer_header.html.erb
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      
      
    </ul>
  </div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
<h3><%= obj.errors.count %> errors prohibited this obj from being saved.</h3>
<ul class="pl-4">
  <% obj.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
 <div class='container mt-5'>
  <div class='row'>
  </div>
 </div>
</footer>

app/views/layouts/_header.html.erb
<div class="collapse navbar-collapse" id="navbarNavDropdown">

  <ul class="navbar-nav ml-auto">

    <% if admin_signed_in? %>
      <li style="margin-right: 10px;">
        <%=  link_to admin_items_path,class: 'nav-link text-dark border border-gray p-1', style: 'border-radius: 5px;'  do %>
          <span class="boxed"> 商品一覧 </span>
        <% end %>
      </li>
      <li style="margin-right: 10px;">
        <%= link_to admin_customers_path,class: 'nav-link text-dark border border-gray p-1', style: 'border-radius: 5px;'  do %>
          <span class="boxed"> 会員一覧 </span>
        <% end %>
      </li>
      <li style="margin-right: 10px;">
        <%=  link_to admin_path ,class: 'nav-link text-dark border border-gray p-1', style: 'border-radius: 5px;'  do %>
          <span class="boxed"> 注文履歴一覧 </span>
        <% end %>
      </li>
      <li style="margin-right: 10px;">
        <%= link_to admin_genres_path, class: 'nav-link text-dark border border-gray p-1', style: 'border-radius: 5px;'  do %>
          <span class="boxed"> ジャンル一覧 </span>
        <% end %>
      </li>
      <li style="margin-right: 10px;">
        <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-dark border border-gray p-1', style: 'border-radius: 5px;'  do %>
          <span class="boxed"> ログアウト </span>
        <% end %>
      </li>

<% elsif customer_signed_in? %>
       <li style="margin: 40px 40px 0 0px;">
    <span>ようこそ、<%= current_customer.last_name %>さん！</span>
  </li>
       <li style="margin-right: 10px;">
          <%= link_to customers_my_page_path(current_customer),class: 'nav-link text-dark border border-gray p-1', style: 'border-radius: 5px;'  do %>

          <span class="boxed"> マイページ </span>
        <% end %>
      </li>
      <li style="margin-right: 10px;">
        <%=  link_to items_path,class: 'nav-link text-dark border border-gray p-1', style: 'border-radius: 5px;'  do %>
          <span class="boxed"> 商品一覧 </span>
        <% end %>
      </li>
      <li style="margin-right: 10px;">
        <%=  link_to cart_items_path ,class: 'nav-link text-dark border border-gray p-1', style: 'border-radius: 5px;'  do %>
          <span class="boxed"> カート </span>
        <% end %>
      </li>
      <li style="margin-right: 10px;">
        <%= link_to destroy_customer_session_path, method: :delete,class: 'nav-link text-dark border border-gray p-1', style: 'border-radius: 5px;'  do %>
          <span class="boxed"> ログアウト </span>

          <% end %>
        </li>
        
<% else %>
     <li style="margin-right: 10px;">
     <%= link_to about_path,class: 'nav-link text-dark border border-gray p-1', style: 'border-radius: 5px;'  do %>
     <span class="boxed"> About </span>
     <% end %>
   </li>
   <li style="margin-right: 10px;">
     <%=  link_to items_path,class: 'nav-link text-dark border border-gray p-1', style: 'border-radius: 5px;'  do %>
     <span class="boxed"> 商品一覧 </span>
     <% end %>
   </li>
   <li style="margin-right: 10px;">
     <%= link_to new_customer_registration_path,class: 'nav-link text-dark border border-gray p-1', style: 'border-radius: 5px;'  do %>
     <span class="boxed"> 新規登録 </span>
     <% end %>
   </li>
   <li style="margin-right: 10px;">
     <%= link_to new_customer_session_path ,class: 'nav-link text-dark border border-gray p-1', style: 'border-radius: 5px;'  do %>
     <span class="boxed"> ログイン </span>
     <% end %>
   </li>
<% end %>


  </ul>
</div>

app/views/layouts/adomin_header.html.erb
<header>
 <nav class="navbar navbar-expand-lg navbar-dark bg-light">
    <div class="container">
      <%= image_tag "logo.png", class: "header-logo", alt: "nagano_cafe" %>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
       </button>
       
       <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%=  link_to admin_items_path,class: 'nav-link text-light' do %>
               <span class="boxed"> 商品一覧 </span>
            <% end %>
          </li>
          <li>
            <%= link_to admin_customers_path,class: 'nav-link text-light' do %>
              <span class="boxed"> 会員一覧 </span>
            <% end %>
          </li>
          <li>
            <%=  link_to adomin_order_details_path ,class: 'nav-link text-light' do %>
              <span class="boxed"> 注文履歴一覧 </span>
            <% end %>
          </li>
          <li>
          <%= link_to destroy_costomers_session_path, method: :delete,class: 'nav-link text-light' do %>
            <span class="boxed"> ログアウト </span>
          <% end %>
        </li>
          <li>
            <%= link_to destroy_adomins_session_path, method: :delete,class: 'nav-link text-light' do %>
              <span class="boxed"> ジャンル一覧 </span>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to about_path,class: 'nav-link text-light' do %>
              <span class="boxed"> about </span>
            <% end %>
          </li>
          <li>
            <%=  link_to items_path,class: 'nav-link text-light' do %>
              <span class="boxed"> 商品一覧 </span>
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_registration_path,class: 'nav-link text-light' do %>
              <span class="boxed"> 新規登録 </span>
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_session_path ,class: 'nav-link text-light' do %>
              <span class="boxed"> ログイン </span>
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
      <div class="search">
    <%= form_with(url: search_path, scope: :item, local: true) do |f| %>
      <%= f.text_field :search, placeholder: "キーワード検索" %>
      <i class="fa-solid fa-magnifying-glass"></i>
      <% f.submit %>
    <% end %>
</div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCafe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/1c6ca0069c.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header style="background-color: mintcream;">
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark">

          
          <%= link_to root_path do %>
            <%= image_tag "logo.png", class: "header-logo", alt: "nagano_cafe", width: "200", height: "50", style: "margin-top: 30px;"  %>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <%= render 'layouts/header' %> 
          </div>
        </nav>

        <div class="search"style="text-align: right; padding-right: 30px;">
          <%= form_with url: keyword_search_path, method: :get, local: true do |f| %>
            <%= f.text_field :keyword, placeholder: "Search" %>
            <%= button_tag(type: 'submit') do %>
              <i class="fa-solid fa-magnifying-glass"></i>
            <% end %>
          <% end %>
        </div>
          
      </div>
      
    </header>

    <main>
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </main>

    <footer>
      <%= render 'layouts/footer' %>
    </footer>

  </body>
</html>